/* CARDINALIDADE */

-- QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGÓCIOS */

/* PRIMEIRO ALGARISMO - OBRIGATORIEDADE 
0 - NÃO OBRIGATÓRIO
1 - OBRIGATÓRIO

SEGUNDO ALGARISMO - CARDINALIDADE
1 - MÁXIMO DE UM
N - MAIS DE UM
*/
