/*

	DML - DATA MANIPULATION LANGUAGE
	DDL - DATA DEFINITION LANGUAGE
	DCL - DATA CONTROL LANGUAGE
	TCL - TRANSACTION CONTROL LANGUAGE

*/

/* DML - DATA MANIPULATION LANGUANGE */

-- INSERT

INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '34678123');
INSERT INTO ENDERECO VALUES(NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 7);

-- FILTROS

SELECT * FROM CLIENTE
WHERE SEXO - 'M';

-- UPDATE

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

-- DELETE

INSERT INTO CLIENTE VALUES(NULL, 'XXX', NULL, 'XXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 8;
