/* DELETANDO REGISTROS COM A CLAÚSULA DELETE */

DELETE FROM CLIENTE;

SELECT * FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- TOTAL 6

SELECT COUNT(*) FROM CLIENTE -- TOTAL DELETADO 1
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- RESTANTE 5

INSERT INTO CLIENTES VALUES('CARLA', 'F', 'C.LOPES@UOL.COM', 781453871, '37318387',
                            'RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE -- OR -> TRAZ TODO MUNDO COM PELO MENOS UMA DAS DUAS CONDIÇÕES
WHERE NOME = 'CARLA'
OR EMAIL = 'CARLA@TERATI.COM';

SELECT * FROM CLIENTE -- AND -> APENAS O REGISTRO QUE SATISFAÇA AS DUAS CONDIÇÕES
WHERE NOME = 'CARLA'
AND EMAIL = 'CARLA@TERATI.COM';

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'CARLA@TERATI.COM';

SELECT * FROM CLIENTE;
