/* DELIMITADOR */

SELECT C.NOME,
	   C.SEXO, 
	   IFNULL(C.EMAIL, 'CLIENTE SEM EMAIL') AS "E-MAIL", 
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO, 
	   E.CIDADE, 
	   E.ESTADO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE

STATUS

DELIMITER $

SELECT * FROM V_RELATORIO$