/* O COMANDO SELECT */

SELECT NOW() AS DATA_HORA, 'BRUNO RIBAS' AS ALUNO;

SELECT 'BRUNO RIBAS';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;

SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECR * FROM CLIENTE;

/* TABELA ERRADA -NÃO DIGITE DIRETAMENTE NO BANCO DE DADOS */

CRETE TABLE CLIENTE(
    NOME VARCHAR(30),
    SEXO CHAR(1),
    EMAIL VARCHAR(30)
    CPT INT (11),
    TELEFONE VARCHAR(30),
    ENDERECO VARCHAR(100),
);
