--! SUBQUERIES

--? VENDEDOR QUE VENDEU MENOS EM MARÇO

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

--? VENDEDOR QUE VENDEU MAIS EM MARÇO

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

--? VENDEDOR(ES) QUE VENDEU ACIMA DA MÉDIA EM FEVEREIRO

SELECT NOME, FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);
