/* VIEW */

SELECT C.NOME, C.SEXO, C.EMAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;
	
CREATE VIEW RELATORIO AS
SELECT C.NOME,
	   C.SEXO, 
	   C.EMAIL, 
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO, 
	   E.CIDADE, 
	   E.ESTADO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT * FROM RELATORIO;

/* APAGANDO UMA VIEW */

DROP VIEW RELATORIO;

/* INSERINDO UM PREFIXO */

CREATE VIEW V_RELATORIO AS
SELECT C.NOME,
	   C.SEXO, 
	   IFNULL(C.EMAIL, 'CLIENTE SEM EMAIL') AS "E-MAIL", 
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO, 
	   E.CIDADE, 
	   E.ESTADO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;

/* UPDATE, INSERT E DELETE - DML */

INSERT INTO V_RELATORIO VALUES(
	'ANDREIA', 'F', 'ANDREIA@UOL.COM.BR', 'CEL', '678643873', 'CENTRO', 'VITORIA', 'ES'
);

ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list

DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';

ERROR 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

/* É PERMITIDO FAZER UPDATES EM VIEWS COM JOIN */

UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';

CREATE TABLE JOGADORES(
	IDJOGADOR INT,
	NOME VARCHAR(30),
	ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES(1, 'GUERREIRO', 'RS');
INSERT INTO JOGADORES VALUES(2, 'GABIGOL', 'RJ');
INSERT INTO JOGADORES VALUES(3, 'GANSO', 'RJ');
INSERT INTO JOGADORES VALUES(4, 'NENE', 'RJ');
INSERT INTO JOGADORES VALUES(5, 'LOVE', 'SP');

CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;

SELECT * FROM V_JOGADORES;

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERREIRO';

SELECT * FROM V_JOGADORES;

INSERT INTO V_JOGADORES VALUES('GUERREIRO', 'RS');

SELECT * FROM JOGADORES;

+-----------+-----------+--------+
| IDJOGADOR | NOME      | ESTADO |
+-----------+-----------+--------+
|         2 | GABIGOL   | RJ     |
|         3 | GANSO     | RJ     |
|         4 | NENE      | RJ     |
|         5 | LOVE      | SP     |
|      NULL | GUERREIRO | RS     |
+-----------+-----------+--------+

SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';